Custom model data
Iridium-Development/IridiumCore pull request #26
Opened 2021-11-21 00:38 UTC by MBDOFF

Adding the posibility to add custom model data to items.

2021-11-21 00:50 UTC, MertUnverdi approved these changes

2021-11-21 00:50 UTC, MertUnverdi commented on plugin/src/main/java/com/iridium/iridiumcore/Item.java
> +     * @param lore        The lore of the item, can be empty
Add a param for model data tho

2021-11-21 00:50 UTC, MertUnverdi commented on plugin/src/main/java/com/iridium/iridiumcore/Item.java
> +    public Item(XMaterial material, int slot, int amount, String displayName, String headOwner, List<String> lore, Integer model) {
U need add some other constructors for items without headdata or slot params etc.

2021-11-21 01:00 UTC, MertUnverdi approved these changes

2021-11-21 10:53 UTC, PeachesMLG commented
With this many constructors, it would be better to implement a builder pattern (with a few default constructors for legacy support)

2021-11-21 11:03 UTC, dlsf commented
I agree with Peaches, it's really getting out of hand now.

But I'm also wondering: How would you use that custom model data option? What kind of integer is that?

2021-11-21 12:58 UTC, MBDOFF commented
I optimized the model data constructors.

2021-11-22 18:17 UTC, PeachesMLG approved these changes

2022-02-23 20:10 UTC, Fantom250YT commented
Any reason this isn't merged?

2022-03-05 23:36 UTC, DoctaEnkoda requested changes

2022-03-05 23:36 UTC, DoctaEnkoda commented on build.gradle.kts
> +version = "1.4.0"
Need rebase

2023-03-31 11:37 UTC, closed without merging